### ISSUE TITLE
[Bug]  1165 crash

### ISSUE THREAD

**Issue by shenjackyuanjie** [Hendrix-Shen/MagicLib#17]
### Minecraft Version

1165

### MagicLib Version

0.7.247

### Description

![image](https://user-images.githubusercontent.com/54507071/227689933-8a97cfdf-fe6b-4584-9691-4ce8bd26badd.png)

### To Reproduce

![image](https://user-images.githubusercontent.com/54507071/227690006-194cbe50-cf8d-4d0f-aa65-3c3a92c8d6ae.png)

### Log

```
[Server] [11:33:54] [main/ERROR]: Mixin apply for mod magiclib-1_16_5 failed magiclib-minecraft-compat-api.mixins.json:math.MixinVector3f from mod magiclib-1_16_5 -> net.minecraft.class_1160: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method method_23214 in magiclib-minecraft-compat-api.mixins.json:math.MixinVector3f from mod magiclib-1_16_5 was not located in the tarn
[Server] org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method method_23214 in magiclib-minecraft-compat-api.mixins.json:math.MixinVector3f from mod magiclib-1_16_5 was not located in the target class net.minecraft.class_1160. Using refmap magiclib-1.16.5-refmap.json
[Server]        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:340) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.11.jar:?]
[Server]        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[Server]        at net.minecraft.class_2457.<clinit>(class_2457.java:73) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2246.<clinit>(class_2246.java:247) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[server-intermediary.jar:?]
[Server]        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) [?:?]
[Server]        at net.minecraft.class_5458.<clinit>(class_5458.java:74) [server-intermediary.jar:?]
[Server]        at net.minecraft.class_2378.<clinit>(class_2378.java:237) [server-intermediary.jar:?]
[Server]        at net.minecraft.class_2966.method_12851(class_2966.java:42) [server-intermediary.jar:?]
[Server]        at net.minecraft.server.Main.main(Main.java:87) [server-intermediary.jar:?]
[Server]        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.11.jar:?]
[Server] [11:33:54] [main/ERROR]: Minecraft has crashed!
[Server] net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
[Server]        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.11.jar:?]
[Server] Caused by: java.lang.ExceptionInInitializerError
[Server]        at net.minecraft.class_2246.<clinit>(class_2246.java:247) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[server-intermediary.jar:?]
[Server]        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
[Server]        at net.minecraft.class_5458.<clinit>(class_5458.java:74) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2378.<clinit>(class_2378.java:237) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.Main.main(Main.java:87) ~[server-intermediary.jar:?]
[Server]        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.11.jar:?]
[Server]        ... 3 more
[Server] Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1160 failed
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.11.jar:?]
[Server]        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[Server]        at net.minecraft.class_2457.<clinit>(class_2457.java:73) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2246.<clinit>(class_2246.java:247) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[server-intermediary.jar:?]
[Server]        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
[Server]        at net.minecraft.class_5458.<clinit>(class_5458.java:74) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2378.<clinit>(class_2378.java:237) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.Main.main(Main.java:87) ~[server-intermediary.jar:?]
[Server]        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.11.jar:?]
[Server]        ... 3 more
[Server] Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[Server]        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.11.jar:?]
[Server]        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[Server]        at net.minecraft.class_2457.<clinit>(class_2457.java:73) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2246.<clinit>(class_2246.java:247) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[server-intermediary.jar:?]
[Server]        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
[Server]        at net.minecraft.class_5458.<clinit>(class_5458.java:74) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2378.<clinit>(class_2378.java:237) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.Main.main(Main.java:87) ~[server-intermediary.jar:?]
[Server]        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.11.jar:?]
[Server]        ... 3 more
[Server] Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [magiclib-minecraft-compat-api.mixins.json:math.MixinVector3f from mod magiclib-1_16_5] from phase [DEFAULT] in config [magiclib-minecraft-compat-api.mixins.json] FAILED during APPLY
[Server]        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.11.jar:?]
[Server]        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[Server]        at net.minecraft.class_2457.<clinit>(class_2457.java:73) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2246.<clinit>(class_2246.java:247) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[server-intermediary.jar:?]
[Server]        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
[Server]        at net.minecraft.class_5458.<clinit>(class_5458.java:74) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2378.<clinit>(class_2378.java:237) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.Main.main(Main.java:87) ~[server-intermediary.jar:?]
[Server]        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.11.jar:?]
[Server]        ... 3 more
[Server] Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method method_23214 in magiclib-minecraft-compat-api.mixins.json:math.MixinVector3f from mod magiclib-1_16_5 was not located in the target class net.minecraft.class_1160. Using refmap magiclib-1.16.5-refmap.json
[Server]        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:340) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.11.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.11.jar:?]
[Server]        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[Server]        at net.minecraft.class_2457.<clinit>(class_2457.java:73) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2246.<clinit>(class_2246.java:247) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[server-intermediary.jar:?]
[Server]        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
[Server]        at net.minecraft.class_5458.<clinit>(class_5458.java:74) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2378.<clinit>(class_2378.java:237) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.Main.main(Main.java:87) ~[server-intermediary.jar:?]
[Server]        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.11.jar:?]
[Server]        ... 3 more
```

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
尝试 [0.7.295+292b8c3](https://github.com/Hendrix-Shen/MagicLib/releases/tag/dev%2F0.7.249) 版本。

**Comment by shenjackyuanjie** [comment]
fixed!
