### ISSUE TITLE
[Bug] 版本错误

### ISSUE THREAD

**Issue by MCtroplus** [Hendrix-Shen/MagicLib#40]
### Minecraft Version

1.20.1

### MagicLib Version

0.7.346

### Description

已安装magiclib 0.7.346，报错提示需要安装0.7.336及以后版本

### To Reproduce

安装magiclib与依赖magiclib的mod的最新版就会报错

### Log
```
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
jlw: native file exists: 'C:\Users\Administrator\AppData\Roaming\PCL\libjlw-1.3.2.dll'.
jlw: native file checked.
[09:49:33] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.21
[09:49:36] [ForkJoinPool-1-worker-2/WARN]: Mod globalpacks uses the version 1.16.1_fabric which isn't compatible with Loader's extended semantic version format (Could not parse version number component '1_fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[09:49:49] [main/WARN]: Mod resolution failed
[09:49:49] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE carpet-tctc-addition 2.2.198+127ab0a-stable {depends magiclib @ [>=0.7.336]}, ROOT_FORCELOAD_SINGLE carpet-tctc-addition 2.2.198+127ab0a-stable]
[09:49:49] [main/INFO]: Reason: [HARD_DEP carpet-tctc-addition 2.2.198+127ab0a-stable {depends magiclib @ [>=0.7.336]}, HARD_DEP lithium 0.11.2 {depends minecraft @ [1.20]}, HARD_DEP masa_gadget_mod 3.2.308+2c7a07f-stable {depends magiclib @ [>=0.7.336]}, HARD_DEP ommc 0.5.289+be50024-dev {depends magiclib @ [>=0.7.324+7be771b-beta]}, HARD_DEP pca 0.3.166+0c5bf4c-beta {depends magiclib @ [>=0.7.336]}, HARD_DEP pca-1_20 0.3.166+0c5bf4c-beta {depends magiclib-1_20 @ [>=0.7.336]}, HARD_DEP pca-1_20 0.3.166+0c5bf4c-beta {depends minecraft @ [1.20]}, HARD_DEP tweakmyclient 3.6.398+b6a4f1b-stable {depends magiclib @ [>=0.7.336]}, HARD_DEP xaero_map_addition 0.2.75+f01c92f-dev {depends magiclib @ [>=0.7.289+4d66634-beta]}, HARD_DEP carpet-tctc-addition-1_20 2.2.198+127ab0a-stable {depends magiclib-1_20 @ [>=0.7.336]}, HARD_DEP carpet-tctc-addition-1_20 2.2.198+127ab0a-stable {depends minecraft @ [1.20]}, HARD_DEP masa_gadget_mod-1_20 3.2.308+2c7a07f-stable {depends magiclib-1_20 @ [>=0.7.336]}, HARD_DEP tweakmyclient-1_20 3.6.398+b6a4f1b-stable {depends magiclib-1_20 @ [>=0.7.336]}]
[09:49:50] [main/INFO]: Fix: add [add:magiclib 0.7.336 ([[0.7.336,鈭?]), add:magiclib-1_20 0.7.336 ([[0.7.336,鈭?])], remove [], replace []
[09:49:50] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install magiclib, version 0.7.336 or later.
	 - Install magiclib-1_20, version 0.7.336 or later.
Unmet dependency listing:
	 - Mod 'Carpet TCTC Addition' (carpet-tctc-addition) 2.2.198+127ab0a-stable requires version 0.7.336 or later of magiclib, which is missing!
	 - Mod 'Lithium' (lithium) 0.11.2 requires version 1.20 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'Masa Gadget' (masa_gadget_mod) 3.2.308+2c7a07f-stable requires version 0.7.336 or later of magiclib, which is missing!
	 - Mod 'Oh My Minecraft Client' (ommc) 0.5.289+be50024-dev requires version 0.7.324+7be771b-beta or later of magiclib, which is missing!
	 - Mod 'Plusls Carpet Addition' (pca) 0.3.166+0c5bf4c-beta requires version 0.7.336 or later of magiclib, which is missing!
	 - Mod 'Plusls Carpet Addition' (pca-1_20) 0.3.166+0c5bf4c-beta requires version 0.7.336 or later of magiclib-1_20, which is missing!
	 - Mod 'Plusls Carpet Addition' (pca-1_20) 0.3.166+0c5bf4c-beta requires version 1.20 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'Tweak My Client' (tweakmyclient) 3.6.398+b6a4f1b-stable requires version 0.7.336 or later of magiclib, which is missing!
	 - Mod 'Xaero Map Addition' (xaero_map_addition) 0.2.75+f01c92f-dev requires version 0.7.289+4d66634-beta or later of magiclib, which is missing!
	 - Mod 'Carpet TCTC Addition for 1.20' (carpet-tctc-addition-1_20) 2.2.198+127ab0a-stable requires version 0.7.336 or later of magiclib-1_20, which is missing!
	 - Mod 'Carpet TCTC Addition for 1.20' (carpet-tctc-addition-1_20) 2.2.198+127ab0a-stable requires version 1.20 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'Masa Gadget for 1.20' (masa_gadget_mod-1_20) 3.2.308+2c7a07f-stable requires version 0.7.336 or later of magiclib-1_20, which is missing!
	 - Mod 'Tweak My Client for 1.20' (tweakmyclient-1_20) 3.6.398+b6a4f1b-stable requires version 0.7.336 or later of magiclib-1_20, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?]
```
### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
请确认你安装的 MagicLib 版本是否标记为 -all，阅读 #7 来确认细节。
