### ISSUE TITLE
新版本masa与魔法类库冲突 他提示我需要下载0.7345 但我已经下载0.7364

### ISSUE THREAD

**Issue by linyiyi1314** [Hendrix-Shen/MagicLib#44]
### Question Type

Codes

### Description
```
[11:09:23] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.21
[11:09:23] [main/WARN]: Mod resolution failed
[11:09:23] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE ommc-1_20_1 0.5.304+a200fcc-beta {depends magiclib-1_20_1 @ [>=0.7.345]}, ROOT_FORCELOAD_SINGLE ommc-1_20_1 0.5.304+a200fcc-beta]
[11:09:23] [main/INFO]: Reason: [HARD_DEP ommc-1_20_1 0.5.304+a200fcc-beta {depends magiclib-1_20_1 @ [>=0.7.345]}]
[11:09:23] [main/INFO]: Fix: add [add:magiclib-1_20_1 0.7.345 ([[0.7.345,∞)])], remove [], replace []
[11:09:23] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install magiclib-1_20_1, version 0.7.345 or later.
Unmet dependency listing:
	 - Mod 'Oh My Minecraft Client for 1.20.1' (ommc-1_20_1) 0.5.304+a200fcc-beta requires version 0.7.345 or later of magiclib-1_20_1, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?]
```

**Comment by Hendrix-Shen** [comment]
参考 #7 解决。
