### ISSUE TITLE
[Bug] masagadget doesnt detect magiclib

### ISSUE THREAD

**Issue by bakjedev** [Hendrix-Shen/MagicLib#6]
### Minecraft Version

1.19.2

### MagicLib Version

0.5.38

### Description

Im not sure if im in the right place but when installing masagadget and magiclib it says that magiclib isnt installed.

### To Reproduce

install masagadget and magiclib 
luanch the game

### Expected behavior

launch

### Log

[21:34:18] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.9
[21:34:18] [main/WARN]: Mod resolution failed
[21:34:18] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE masa_gadget_mod 3.0.0 {depends magiclib @ [>=0.5.30]}, ROOT_FORCELOAD_SINGLE masa_gadget_mod 3.0.0]
[21:34:18] [main/INFO]: Reason: [HARD_DEP masa_gadget_mod 3.0.0 {depends magiclib @ [>=0.5.30]}]
[21:34:18] [main/INFO]: Fix: add [add:magiclib 0.5.30 ([[0.5.30,∞)])], remove [], replace []
[21:34:18] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install magiclib, version 0.5.30 or later.
Unmet dependency listing:
	 - Mod 'Masa Gadget' (masa_gadget_mod) 3.0.0 requires version 0.5.30 or later of magiclib, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
See https://github.com/Hendrix-Shen/MagicLib/issues/7.

**Comment by bakjedev** [comment]
still doesnt launch

**Comment by Hendrix-Shen** [comment]
Upload your log. You should use MasaGadget [3.0.0-beta+0d38417](https://github.com/plusls/MasaGadget/suites/7919009900/artifacts/337365588) in MC 1.19.2.
